---
title: "Club Soccer Predictions"
author: "ds202_finalProjectTeam3 github.com/shasan2519/ds202_finalProjectTeam3"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Team Meber: Syed Hasan, Connor Carpenter, Orion Hunter
### Link: https://github.com/fivethirtyeight/data/blob/master/soccer-spi/README.md

# Summary of the link:
  - This file contains links to the data behind our Club Soccer Predictions and Global Club Soccer Rankings.

spi_matches.csv contains match-by-match SPI ratings and forecasts back to 2016.

spi_global_rankings.csv contains current SPI ratings and rankings for men's club teams.

spi_global_rankings_intl.csv contains current SPI ratings and rankings for men's international teams.
  
# Question we are planning to answer:
  - Underlying quality of play
  - Once we’ve established ratings for every team in the leagues we cover, we forecast the outcomes of upcoming matches with a Poisson model that forecasts the estimated number of goals we expect each team to score.
  -One challenge when building such a system is the large number of leagues around the world: we have over 400 in our database. What teams will be best for this project?
  -Do we compare soccer teams from all the regions or only the US based soccer, this will be based on which region has less data missing.